- name: Provision Kubernetes Nodes
  hosts: localhost
  gather_facts: no
  vars_files:
  - vars/{{ env }}.yml
  - secrets.yml
  roles:
    - role: provision_nodes

- name: Configure Kubernetes Nodes
  hosts: all_nodes
  gather_facts: yes
  vars:
    ansible_ssh_common_args: "-o ConnectTimeout=5 -o ConnectionAttempts=5"
  roles:
    - configure_nodes

