- name: Ensure Kubernetes apt keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes apt key to keyring
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  ansible.builtin.shell:
    cmd: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
    creates: /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages for Kubernetes
  apt:
    name:
      - kubelet=1.28.15-1.1
      - kubeadm=1.28.15-1.1
      - kubectl=1.28.15-1.1
    state: present
    update_cache: yes
  register: install_result
  retries: 5
  delay: 30
  until: install_result is succeeded

- name: Ensure services are enabled and running
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - kubelet

